# Generated by Django 3.2.9 on 2021-12-21 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Traducao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('morse', models.CharField(max_length=500)),
                ('texto', models.CharField(max_length=500)),
            ],
        ),
    ]
