# Generated by Django 3.2.9 on 2021-12-22 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_principal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TraducaoMorse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('morse', models.TextField(max_length=1000)),
                ('texto', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='TraducaoTexto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(max_length=1000)),
                ('morse', models.TextField(max_length=2500)),
            ],
        ),
        migrations.DeleteModel(
            name='Traducao',
        ),
    ]
